default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  strict: false

development:
  <<: *default
  database: cf_dev
  username: root
  password: 

